# pandas example
>read_html 사용하여 html파일 내의 자료 불러오기

In [76]:
import pandas as pd

#html에서 코드 읽기,header와 index 정하기(1번 열에 나라 이름)
df = pd.read_html('https://olympics.com/tokyo-2020/olympic-games/en/results/all-sports/medal-standings.htm',header=0,index_col=1)

tokyo = df[0].iloc[:,:5]

### iloc[a:b,c:d]
> a부터b행까지, c열부터d열까지

In [77]:
tokyo.columns = ['순위','금','은','동','계']    #열 이름 정하기
tokyo = tokyo.sort_values('금',ascending=False)    #sort_values('열 이름')로 기준 정해서 정렬

tokyo

                            순위   금   은   동    계
Team/NOC
United States of America     1  39  41  33  113
People's Republic of China   2  38  32  18   88
Japan                        3  27  14  17   58
Great Britain                4  22  21  22   65
ROC                          5  20  28  23   71
...                         ..  ..  ..  ..  ...
Armenia                     69   0   2   2    4
Dominican Republic          68   0   3   2    5
Azerbaijan                  67   0   3   4    7
Colombia                    66   0   4   1    5
Syrian Arab Republic        86   0   0   1    1

[93 rows x 5 columns]

## 위의 자료를 엑셀 형태로 저장
>to_excel

In [78]:
tokyo.to_excel('도쿄올림픽메달.xlsx')

PermissionError: [Errno 13] Permission denied: '도쿄올림픽메달.xlsx'

# 데이터 프레임 기초
### DataFrame = 2차원 형태의 데이터

In [79]:
# date_range('일/월/년',periods=기간)
index = pd.date_range('1/1/2021',periods = 60)
print(index)

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
               '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
               '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
               '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
               '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
               '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
               '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01',
               '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05',
               '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09',
               '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13',
               '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17',
               '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21',
               '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25',
               '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01'],
              dtype='datetime64[ns]', freq='D')

In [91]:
import numpy as np
df = pd.DataFrame(np.random.rand(60,3),index = index,columns=list('ABC'))
df

                   A         B         C
2021-01-01  0.692531  0.081832  0.114507
2021-01-02  0.529163  0.023010  0.650190
2021-01-03  0.293380  0.365133  0.165451
2021-01-04  0.469406  0.733800  0.480060
2021-01-05  0.989859  0.209799  0.720225
2021-01-06  0.473564  0.131907  0.466960
2021-01-07  0.000864  0.060978  0.279573
2021-01-08  0.187666  0.595049  0.464896
2021-01-09  0.726301  0.366528  0.503169
2021-01-10  0.206482  0.577598  0.938978
2021-01-11  0.128948  0.898637  0.870171
2021-01-12  0.136585  0.090280  0.890586
2021-01-13  0.747572  0.507572  0.133121
2021-01-14  0.646874  0.931602  0.394430
2021-01-15  0.674212  0.723379  0.515704
2021-01-16  0.287613  0.575157  0.032820
2021-01-17  0.667455  0.982866  0.048928
2021-01-18  0.070333  0.159954  0.906484
2021-01-19  0.755594  0.811054  0.876789
2021-01-20  0.767573  0.549569  0.330457
2021-01-21  0.971549  0.317917  0.731886
2021-01-22  0.460169  0.158786  0.510192
2021-01-23  0.519051  0.433107  0.519469
2021-01-24  0.075504  0.716685  0.713014
2021-01-25  0.756836  0.151293  0.330539
2021-01-26  0.145991  0.999759  0.349135
2021-01-27  0.632503  0.925150  0.828247
2021-01-28  0.553618  0.682956  0.898477
2021-01-29  0.606495  0.644492  0.595646
2021-01-30  0.792232  0.296188  0.604779
2021-01-31  0.001623  0.114828  0.349202
2021-02-01  0.919515  0.247586  0.315594
2021-02-02  0.010887  0.191644  0.240383
2021-02-03  0.811163  0.632291  0.704279
2021-02-04  0.215035  0.254348  0.102689
2021-02-05  0.054332  0.048195  0.490798
2021-02-06  0.516071  0.929617  0.185090
2021-02-07  0.217663  0.134621  0.534600
2021-02-08  0.508305  0.753798  0.748080
2021-02-09  0.676005  0.201067  0.222356
2021-02-10  0.379641  0.870895  0.624931
2021-02-11  0.405295  0.229889  0.158490
2021-02-12  0.307335  0.325551  0.239194
2021-02-13  0.225650  0.056085  0.059895
2021-02-14  0.655027  0.086255  0.806354
2021-02-15  0.955885  0.399697  0.837459
2021-02-16  0.946483  0.658501  0.107758
2021-02-17  0.993367  0.597807  0.935095
2021-02-18  0.449879  0.302038  0.026242
2021-02-19  0.374259  0.987776  0.792254
2021-02-20  0.129373  0.677009  0.672618
2021-02-21  0.717052  0.496019  0.341896
2021-02-22  0.743520  0.347453  0.222702
2021-02-23  0.402699  0.373741  0.091077
2021-02-24  0.751782  0.040637  0.369910
2021-02-25  0.942603  0.723889  0.915636
2021-02-26  0.782883  0.517064  0.563514
2021-02-27  0.662117  0.158058  0.363102
2021-02-28  0.448540  0.219605  0.340281
2021-03-01  0.197260  0.303500  0.387804

In [92]:
# mask 적용 가능

mask = df['B'] > 0.7

df[mask]

                   A         B         C
2021-01-04  0.469406  0.733800  0.480060
2021-01-11  0.128948  0.898637  0.870171
2021-01-14  0.646874  0.931602  0.394430
2021-01-15  0.674212  0.723379  0.515704
2021-01-17  0.667455  0.982866  0.048928
2021-01-19  0.755594  0.811054  0.876789
2021-01-24  0.075504  0.716685  0.713014
2021-01-26  0.145991  0.999759  0.349135
2021-01-27  0.632503  0.925150  0.828247
2021-02-06  0.516071  0.929617  0.185090
2021-02-08  0.508305  0.753798  0.748080
2021-02-10  0.379641  0.870895  0.624931
2021-02-19  0.374259  0.987776  0.792254
2021-02-25  0.942603  0.723889  0.915636

### 새로운 열 생성하기

In [94]:
df['D'] = df['A']/df['B']

df

                   A         B         C          D
2021-01-01  0.692531  0.081832  0.114507   8.462876
2021-01-02  0.529163  0.023010  0.650190  22.997431
2021-01-03  0.293380  0.365133  0.165451   0.803490
2021-01-04  0.469406  0.733800  0.480060   0.639691
2021-01-05  0.989859  0.209799  0.720225   4.718140
2021-01-06  0.473564  0.131907  0.466960   3.590144
2021-01-07  0.000864  0.060978  0.279573   0.014175
2021-01-08  0.187666  0.595049  0.464896   0.315379
2021-01-09  0.726301  0.366528  0.503169   1.981569
2021-01-10  0.206482  0.577598  0.938978   0.357484
2021-01-11  0.128948  0.898637  0.870171   0.143492
2021-01-12  0.136585  0.090280  0.890586   1.512894
2021-01-13  0.747572  0.507572  0.133121   1.472841
2021-01-14  0.646874  0.931602  0.394430   0.694367
2021-01-15  0.674212  0.723379  0.515704   0.932032
2021-01-16  0.287613  0.575157  0.032820   0.500060
2021-01-17  0.667455  0.982866  0.048928   0.679091
2021-01-18  0.070333  0.159954  0.906484   0.439707
2021-01-19  0.755594  0.811054  0.876789   0.931620
2021-01-20  0.767573  0.549569  0.330457   1.396682
2021-01-21  0.971549  0.317917  0.731886   3.055986
2021-01-22  0.460169  0.158786  0.510192   2.898047
2021-01-23  0.519051  0.433107  0.519469   1.198437
2021-01-24  0.075504  0.716685  0.713014   0.105352
2021-01-25  0.756836  0.151293  0.330539   5.002446
2021-01-26  0.145991  0.999759  0.349135   0.146026
2021-01-27  0.632503  0.925150  0.828247   0.683676
2021-01-28  0.553618  0.682956  0.898477   0.810620
2021-01-29  0.606495  0.644492  0.595646   0.941043
2021-01-30  0.792232  0.296188  0.604779   2.674756
2021-01-31  0.001623  0.114828  0.349202   0.014132
2021-02-01  0.919515  0.247586  0.315594   3.713915
2021-02-02  0.010887  0.191644  0.240383   0.056806
2021-02-03  0.811163  0.632291  0.704279   1.282896
2021-02-04  0.215035  0.254348  0.102689   0.845434
2021-02-05  0.054332  0.048195  0.490798   1.127333
2021-02-06  0.516071  0.929617  0.185090   0.555144
2021-02-07  0.217663  0.134621  0.534600   1.616862
2021-02-08  0.508305  0.753798  0.748080   0.674325
2021-02-09  0.676005  0.201067  0.222356   3.362093
2021-02-10  0.379641  0.870895  0.624931   0.435920
2021-02-11  0.405295  0.229889  0.158490   1.763006
2021-02-12  0.307335  0.325551  0.239194   0.944046
2021-02-13  0.225650  0.056085  0.059895   4.023391
2021-02-14  0.655027  0.086255  0.806354   7.594082
2021-02-15  0.955885  0.399697  0.837459   2.391523
2021-02-16  0.946483  0.658501  0.107758   1.437329
2021-02-17  0.993367  0.597807  0.935095   1.661687
2021-02-18  0.449879  0.302038  0.026242   1.489479
2021-02-19  0.374259  0.987776  0.792254   0.378890
2021-02-20  0.129373  0.677009  0.672618   0.191095
2021-02-21  0.717052  0.496019  0.341896   1.445615
2021-02-22  0.743520  0.347453  0.222702   2.139916
2021-02-23  0.402699  0.373741  0.091077   1.077483
2021-02-24  0.751782  0.040637  0.369910  18.499827
2021-02-25  0.942603  0.723889  0.915636   1.302137
2021-02-26  0.782883  0.517064  0.563514   1.514095
2021-02-27  0.662117  0.158058  0.363102   4.189062
2021-02-28  0.448540  0.219605  0.340281   2.042482
2021-03-01  0.197260  0.303500  0.387804   0.649951

### axis = 0이면 열 기준, 1이면 행 기준

In [95]:
df['E'] = np.sum(df,axis=1)

df.head()   #처음 5개의 데이터만 출력하는 코드

                   A         B         C          D          E
2021-01-01  0.692531  0.081832  0.114507   8.462876   9.351746
2021-01-02  0.529163  0.023010  0.650190  22.997431  24.199794
2021-01-03  0.293380  0.365133  0.165451   0.803490   1.627454
2021-01-04  0.469406  0.733800  0.480060   0.639691   2.322957
2021-01-05  0.989859  0.209799  0.720225   4.718140   6.638022

In [97]:
df = df.sub(df['A'],axis = 0)
df.head()

              A         B         C          D          E
2021-01-01  0.0 -0.610700 -0.578024   7.770344   8.659215
2021-01-02  0.0 -0.506154  0.121027  22.468268  23.670631
2021-01-03  0.0  0.071752 -0.127930   0.510109   1.334073
2021-01-04  0.0  0.264394  0.010654   0.170286   1.853551
2021-01-05  0.0 -0.780061 -0.269635   3.728281   5.648163

### csv파일로 저장하기

In [98]:
df.to_csv('test.csv')